// This file was generated by RedwoodJS
import AboutPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/AboutPage/AboutPage'
import FatalErrorPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/HomePage/HomePage'
import MakeProfilePageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/MakeProfilePage/MakeProfilePage'
import NotFoundPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/NotFoundPage/NotFoundPage'
import OverviewDatacratesPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/OverviewDatacratesPage/OverviewDatacratesPage'
import OverviewProfilesPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/OverviewProfilesPage/OverviewProfilesPage'
import OverviewSpacesPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/OverviewSpacesPage/OverviewSpacesPage'
import SettingsPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SettingsPage/SettingsPage'
import SpecificDatacrateContentPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SpecificDatacrateContentPage/SpecificDatacrateContentPage'
import SpecificDatacrateGitPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SpecificDatacrateGitPage/SpecificDatacrateGitPage'
import SpecificDatacratePageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SpecificDatacratePage/SpecificDatacratePage'
import SpecificDatacratePageNodePageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SpecificDatacratePageNodePage/SpecificDatacratePageNodePage'
import SpecificDatacrateSettingsPageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SpecificDatacrateSettingsPage/SpecificDatacrateSettingsPage'
import SpecificProfilePageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SpecificProfilePage/SpecificProfilePage'
import SpecificSpacePageType from 'C:/Users/cedric/Documents/GitHub/dmbon-assistant/frontend/web/src/pages/SpecificSpacePage/SpecificSpacePage'

declare global {
  const AboutPage: typeof AboutPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const MakeProfilePage: typeof MakeProfilePageType
  const NotFoundPage: typeof NotFoundPageType
  const OverviewDatacratesPage: typeof OverviewDatacratesPageType
  const OverviewProfilesPage: typeof OverviewProfilesPageType
  const OverviewSpacesPage: typeof OverviewSpacesPageType
  const SettingsPage: typeof SettingsPageType
  const SpecificDatacrateContentPage: typeof SpecificDatacrateContentPageType
  const SpecificDatacrateGitPage: typeof SpecificDatacrateGitPageType
  const SpecificDatacratePage: typeof SpecificDatacratePageType
  const SpecificDatacratePageNodePage: typeof SpecificDatacratePageNodePageType
  const SpecificDatacrateSettingsPage: typeof SpecificDatacrateSettingsPageType
  const SpecificProfilePage: typeof SpecificProfilePageType
  const SpecificSpacePage: typeof SpecificSpacePageType
}
